Should print awserr code and message instead of pointer
otm/sshauth pull request #6
Opened 2016-09-29 13:16 UTC by ilons

Instead of printing pointer addresses the string should be printed when printing debug and errors.

2016-09-29 14:43 UTC, ilons commented
Added option to set syslog as log writer instead of printing on stdout
Fixed several issues where an memory address would be printed instead of the message for errors

2016-10-03 15:10 UTC, otm requested changes

2016-10-03 15:10 UTC, otm commented on main.go
> +	debug = "False"
Create debug const, and add option

2016-10-03 15:10 UTC, otm commented on main.go
> + -logger             Target for logs, stdout or syslog
syntax for writing options

2016-10-03 15:10 UTC, otm commented on main.go
> +			log.Fatal(usage)
Do not use log fatal

2016-10-03 15:10 UTC, otm commented on main.go
> +	log.SetFlags(0)
Please leave timestamps for stdout

2016-10-03 15:10 UTC, otm commented on main.go
> +	if *logger != "stdout" && *logger != "syslog" {
swith statement

2016-10-03 15:10 UTC, otm commented on main.go
> +		log.Fatalf("Unknown logger '%s' specified", *logger)
Unknown logger specified: %s

2016-10-03 15:10 UTC, otm commented on main.go
> +		log.Println(sshlogger)
This should print to stdout

2016-10-03 15:10 UTC, otm commented on main.go
> +func printErr(s ...interface{}) {
Remove

2016-10-03 15:10 UTC, otm commented on main.go
> +		log.Print(fmt.Sprintf(" * %v", s...))
This fails if length of s is not "1"
Let's skip the "*"

2016-10-03 15:10 UTC, otm commented on main.go
> +			printDbgf("AWS Error(1) Code: %s, Message: %s", awsErr.Code(), awsErr.Message())
This should be log.Print

2016-10-03 15:10 UTC, otm commented on main.go
> +
Add debug flag

2019-01-16 15:03 UTC, closed without merging